import React from "react";
import Navbar1 from "../../home/Navbar1";
import Footer from "../../footer/footer";

const Cookies = () => {
  return (
    <>
      <Navbar1 />

      <div className="COOKIES ">
        <div className="container">
        <div className="titel" style={{ textAlign: "center" }}>
          <h2>COOKIES POLICY</h2>
        </div>
          <h4>Introduction</h4> <br />
          <p>
            Property Finder respects your privacy, and we are committed to being
            transparent about the technologies that we use. We provide this
            Cookies Policy to explain how and <br />
            why cookies, tracking pixels and other similar technologies may be
            stored on and accessed from your device when you use or visit our
            websites <br />
            or our mobile applications. This Cookies Policy should be read
            together with our Privacy Policy and Terms of Use <br />
            In this Policy, “Property Finder”, “we” or “us” refers to
            Propertyfinder FZ-LLC and its subsidiaries and affiliates.
          </p>{" "}
          <br />
          <h4>Use of cookies</h4> <br />
          <p>
            Like many websites, this website uses cookies (which may also be
            placed and read by third party providers, including but not limited
            to Google Analytics), which are files <br />
            collect data and store information on your hard drive. Cookies are
            used for purposes that include but are not limited to allowing the
            user of such information or the website <br />
            identify account holders, track new users, record session
            information, and generally to optimize your experience. <br />
            Most browsers accept cookies automatically but if you choose you can
            disable the cookies from your browser. However, you may find that
            certain functions and features will not work as intended on the
            services that you require.
          </p>
          <h4>Use of third party analytics and tracking pixels</h4>
          <p>
            This website uses third party analytics (“Third Party Analytics”).
            Third Party Analytics use cookies and/or text files to analyse
            website traffic. Information generated by <br /> cookies with your
            details (including your IP address) is transferred to servers
            operated by Third Party Analytics. Third Party Analytics process
            this information to evaluate your use of <br /> this website,
            compile reports about this website’s activity on our behalf, and
            deliver other related services regarding website and Internet use.
            Third Party Analytics may also <br /> share this information with
            third parties insofar as this is necessary or if these third parties
            process the information on behalf of them. You may disable the
            cookies from your <br />
            browser by adjusting your browser settings. However, in this
            scenario, you may not be able to make full use of all the functions
            available on this website. Third party tracking pixels are used on
            our website. This means that third parties may use cookies, web
            beacons, and similar technologies to collect or receive information
            from our website and elsewhere on the internet and use that
            information to provide measurement services and target adverts. If
            you wish to opt out of the use of these tracking pixels please
            adjust your browser settings.
          </p>
          <h4>Web server and application logs</h4>
          <p>
            Our servers automatically collect certain information to help us
            administer and protect our services, analyse usage, and improve
            users’ experience. The information <br /> collected includes,
            amongst others:
          </p>
          <ol>
            <li>IP address and browser type</li>
            <li>
              Device information including Unique Device Identifier (UDID), MAC
              address, Identifier For Advertisers (IFA), and similar identifiers
              we or others may assign
            </li>
            <li>Device operating system and other technical facts</li>
            <li>Pages visited and content viewed, stored, and purchased</li>
            <li>Information or text entered</li>
            <li>Links and buttons clicked</li>
            <li>URLs visited before and after you use our Services</li>
          </ol>
          <h4>Third party advertisers</h4>
          <p>
            We allow third party advertising networks to serve advertisements on
            our behalf. Third party advertisers may place cookies on the
            browsers of visitors to its website(s) and may send its own cookies
            to the visitors’ cookie file. The cookies will allow these
            third-party advertisers to apply their personalized retargeting
            technology and to serve personalized banners; third party
            advertisers may collect and use this data in accordance with all
            applicable laws and regulations (including but not limited to laws
            governing privacy and data protection). Third party advertisers will
            have their own privacy policies, and these will be available on
            their websites.
          </p>
          <h4>Interest-based advertising (IBA)</h4>
          <p>
            Interest-based advertising (IBA) allows us to deliver targeted
            advertising to users of our services. IBA works by showing you
            advertisements that are based on the type of content you access or
            read. For example, as you browse our services, one of the cookies
            placed on your device will be an advertising cookie so we can better
            understand what sort of pages or content you are interested in. The
            information collected about your device enables us to group you with
            other devices that have shown similar interests. We can then display
            advertising to categories of users that is based on common
            interests. If you want to opt out of receiving interest-based
            advertising, it does not mean that you will no longer receive
            advertising when you are using our services. It just means that we
            will not use information collected about you for IBA and that any
            advertising you see will not be customized or relevant to you.
            Please note that if you delete cookies, use a different device, or
            change web browsers, you may need to opt out again. Mobile devices
            have an identifier that gives companies the ability to serve
            targeted ads to a specific mobile device. In many cases, you can
            turn off mobile device ad tracking or you can reset the advertising
            identifier at any time within your mobile device privacy settings.
            You may also choose to turn off location tracking on your mobile
            device. If you turn off ad tracking or location tracking, we will no
            longer use information collected from your device’s advertising
            identifier for the purposes of advertising. You may still see the
            same number of ads but they may be less relevant because they will
            not be based on your interests.
          </p>
        </div>
      </div>

      <Footer />
    </>
  );
};

export default Cookies;
